language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.2

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

    # System images to run emulator(s) during tests.
    #- sys-img-armeabi-v7a-android-27


# Cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


script:
  - gradle build
