language: android
jdk: oraclejdk8
sudo: required

env:
  global:
   # Increase timeout for installation to 8 minutes. Default is 2.
    - ADB_INSTALL_TIMEOUT=8
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

addons:
  sonarcloud:
    organization: "federicoguerri-github"
    token:
        secure: ${SONAR}
    
android:
  components:
    - build-tools-27.0.3
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    
install:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  
  # Install the rest of tools.
  - sdkmanager tools
  
  # Install the system image.
  - sdkmanager "system-images;android-22;default;armeabi-v7a"
    
  # Create and start emulator for the script.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-22;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

script:
  # Run junit tests
  - ./gradlew testDebugUnitTestCoverage

  # Wait emulator and unlock it.
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # Tapping on "WAIT" button of dialog
  - adb shell input tap 297 478 &
  - sleep 2
  - adb shell input tap 305 484 &
  - sleep 2
  - adb shell input tap 320 490 &
  - sleep 2

  - adb shell input keyevent 82 &

  # Run instrumentation tests and wait for result for 50 minutes
  - travis_wait 50 ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.size=large
  
  -./gradlew sonarqube \
  -Dsonar.projectKey=internship_android \
  -Dsonar.organization=federicoguerri-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=fe32e036621d120260a2e306a4b470a4e55f7404

after_success:
  # Upload coverage to coveralls
  - ./gradlew coveralls
  
notifications:
    email:
      recipients:
        - fede95gg@gmail.com
      on_success: change
      on_failure: change
