language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=6
  
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    
    #Android version used 
    - android-24

    #Addictional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    
    #Emulator image
    - sys-img-armeabi-v7a-android-24
   
   
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

#Licenses agreement and codecov installation
before_install:
  - yes | sdkmanager "platforms;android-24"
  - yes | sdkmanager "platforms;android-27"
  - pip install --user codecov

#run jacoco and instrumentation tests
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - android list targets
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -camera-back emulated -camera-front emulated &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb devices
  – sleep 800
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck

after_success:
    - codecov
    
notifications:
    email:
      recipients:
        - fede95gg@gmail.com
      on_success: change
      on_failure: never
