language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=6

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2 #27
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
    - sys-img-armeabi-v7a-android-25

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-25"
  - yes | sdkmanager "platforms;android-27"
  - pip install --user codecov

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck

after_success:
    - codecov
    
notifications:
    email:
      recipients:
        - fede95gg@gmail.com
      on_success: change
      on_failure: never
