language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-android-24

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "platforms;android-27"
  - pip install --user codecov

script:
  - sdkmanager "system-images;android-24;default;armeabi-v7a"
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t "system-images;android-24;default;armeabi-v7a"
  #- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window -camera-back emulated -camera-front emulated -memory 2048 -writable-system &
  - adb wait-for-device
  - adb remount
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb devices
  - sleep 5
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck

after_success:
    - codecov
    
notifications:
    email:
      recipients:
        - fede95gg@gmail.com
      on_success: change
      on_failure: never
