# CircleCi configuration version
version: 2

jobs:
  build:
    docker:
      # specific environment version to avoid incompatible updates
      - image: bitriseio/docker-android:v2017_09_09-06_45-b744

    working_directory: ~/workspace

    steps:
    
      - run:
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb

      - run:
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb
            
      - run:
          name: Making license directory
          command: mkdir "$ANDROID_HOME/licenses" || true
          environment:
            TERM: dumb
            
      - run:
          name: Licenses
          command: echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
          environment:
            TERM: dumb

      - run:
          name: Create avd
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - checkout

      - run:
          name: Permission to wait-script
          command: chmod +x android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Unit testing
          command: ./gradlew testDebugUnitTestCoverage
          environment:
            TERM: dumb

      - run:
          name: Instrumentation testing
          command: ./gradlew connectedCheck
          environment:
            TERM: dumb
            
deployment:
  coverage:
    branch: [master]
    commands:
      - bash <(curl -s https://codecov.io/bash)
